SELECT * FROM Empleado;
SELECT TIPO FROM TIPO_MOTO;
SELECT * FROM CLIENTE;
SELECT * FROM EMPLEADO;
SELECT * FROM DIRECCION;
SELECT * FROM SUCURSAL;
SELECT * FROM COLOR;
SELECT * FROM MARCA;
SELECT * FROM VENTA;
SELECT * FROM DETALLE_VENTA;
SELECT * FROM MOTO;



